<?php

namespace AppBundle\Repository;

/**
 * ArtRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
use Knp\Component\Pager\Paginator;
use Symfony\Component\HttpFoundation\Request;
use AppBundle\Entity\Art;
class ArtRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByPage(Paginator $paginator, Request $request){

        $dql   = "SELECT a FROM AppBundle:Art a ORDER BY a.id DESC";
        $query = $this->getEntityManager()->createQuery($dql);

        $pagination = $paginator->paginate(
            $query,
            $request->query->get('page', 1)/*page number*/,
            Art::NUM_ITEMS/*limit per page*/
        );
        return $pagination;
    }
}
