<?php

namespace AppBundle\Repository;

/**
 * LikeNoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LikeNoRepository extends \Doctrine\ORM\EntityRepository
{
}
