<?php

namespace AppBundle\Repository;

/**
 * MsgRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MsgRepository extends \Doctrine\ORM\EntityRepository
{
}
